src/objects/SMSConfiguration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>SMSConfiguration Hierarchy Custom Setting</description>
    <fields>
        <fullName>Confirmation_Keyword__c</fullName>
        <description>confirmation text field</description>
        <inlineHelpText>Confirmation text field</inlineHelpText>
        <label>Confirmation Keyword</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Follow_up_keyword__c</fullName>
        <description>followup task on keyword</description>
        <inlineHelpText>followup task on keyword</inlineHelpText>
        <label>Follow up keyword</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Appointment_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Send Appointment Confirmation with following template</description>
        <inlineHelpText>Send Appointment Confirmation with following template</inlineHelpText>
        <label>Service Appointment Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Appointment_Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Send Appointment Reminder</description>
        <inlineHelpText>Send Appointment Reminder</inlineHelpText>
        <label>Service Appointment Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X1_Hour_Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>1 Hour Reminder</description>
        <inlineHelpText>1 Hour Reminder</inlineHelpText>
        <label>1 Hour Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X24_Hour_Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>24 Hour prior</description>
        <inlineHelpText>24 Hour prior</inlineHelpText>
        <label>24 Hour Reminder</label>
        <type>Checkbox</type>
    </fields>
    <label>SMSConfiguration</label>
</CustomObject>

src/classes/ServicePortalTest.cls
@isTest
public class ServicePortalTest 
{
    
	public static testMethod void SendAppointmentTest()
    { 
        //Inserting Test Data - Custom Setting
        SMSConfiguration__c data = new SMSConfiguration__c();     
        data.Service_Appointment_Confirmation__c=true; 
        insert data;
        
	    ServiceController.SendAppointment(true); 
        SMSConfiguration__c con=[select id, Service_Appointment_Confirmation__c from SMSConfiguration__c Limit 1];
        System.assertEquals(true,con.Service_Appointment_Confirmation__c);
        
        ServiceController.SendAppointment(false);
        SMSConfiguration__c con1=[select id, Service_Appointment_Confirmation__c from SMSConfiguration__c Limit 1];
        System.assertEquals(false,con1.Service_Appointment_Confirmation__c);      
    }
    
    public static testMethod void KeywordTest()
    { 
        //Inserting Test Data - Custom Setting
        SMSConfiguration__c data = new SMSConfiguration__c();
        data.Confirmation_Keyword__c = 'Yes';
        data.Follow_up_keyword__c = 'Maybe';
        data.Service_Appointment_Confirmation__c=true;
        insert data;
        
	    ServiceController.updatebothKeyword('Yes', 'Maybe');
        SMSConfiguration__c con=[select id, Confirmation_Keyword__c,Follow_up_keyword__c from SMSConfiguration__c Limit 1];
        System.assertEquals('Yes',con.Confirmation_Keyword__c);
        System.assertEquals('Maybe',con.Follow_up_keyword__c);
        
        ServiceController.updatebothKeyword(Null, Null);
        SMSConfiguration__c con1=[select id, Confirmation_Keyword__c,Follow_up_keyword__c from SMSConfiguration__c Limit 1];
        System.assertEquals(Null,con1.Confirmation_Keyword__c);
        System.assertEquals(Null,con1.Follow_up_keyword__c);
               
    }
    
    public static testMethod void SendRemainderTesttrueCheck()
    { 
        //Inserting Test Data - Custom Setting
        SMSConfiguration__c data = new SMSConfiguration__c();
        data.Confirmation_Keyword__c = 'Yes';
        data.Follow_up_keyword__c = 'Maybe';
        data.Name='test data';
        data.Service_Appointment_Confirmation__c=true;
        data.Service_Appointment_Reminder__c = True;
        data.X1_Hour_Reminder__c = true;
        data.X24_Hour_Reminder__c = true;
        insert data;
         
	    ServiceController.ServiceReminder(true);
        ServiceController.x1HourReminder(true);
        ServiceController.x24HourReminder(true);
        
        SMSConfiguration__c con=[select id, Service_Appointment_Reminder__c,X1_Hour_Reminder__c,X24_Hour_Reminder__c from SMSConfiguration__c Limit 1];
        System.assertEquals(true,con.Service_Appointment_Reminder__c);
        System.assertEquals(true,con.X1_Hour_Reminder__c);
        System.assertEquals(true,con.X24_Hour_Reminder__c);
        
            
    }
    
     public static testMethod void SendRemainderTestFalseCheck()
    {
        //Inserting Test Data - Custom Setting
        SMSConfiguration__c data = new SMSConfiguration__c();
        data.Service_Appointment_Reminder__c = false;
        data.X1_Hour_Reminder__c = false;
        data.X24_Hour_Reminder__c = false;
        insert data;
        
        ServiceController.ServiceReminder(false);
        ServiceController.x1HourReminder(false);
        ServiceController.x24HourReminder(false);
        SMSConfiguration__c con1=[select id, Service_Appointment_Reminder__c,X1_Hour_Reminder__c,X24_Hour_Reminder__c from SMSConfiguration__c Limit 1];
        System.assertEquals(false,con1.Service_Appointment_Reminder__c);
        System.assertEquals(false,con1.X1_Hour_Reminder__c);
        System.assertEquals(false,con1.X24_Hour_Reminder__c);  
    }
  
}